export const surpriseMePrompts = [
  "An armchair in the shape of a banana",
  "A surrealist dream-like oil painting of a dog playing chess by Salvador Dalí",
  "Teddy bears on a shopping trip in Paris, in ukiyo-e style",
  "A digital art piece of a robot playing a musical instrument by Matisse",
  "A panda scientist working with glowing chemicals in digital art",
  "A macro 35mm photograph of two elephants in Africa, each wearing safari hats and carrying cameras, in digital art",
  "A 3D render of a cute tropical bird in a jungle setting on a bright green background, in digital art",
  "An astronaut taking a break in a luxurious space hotel, in vaporwave style",
  "An oil painting portrait of a raccoon wearing a top hat and monocle on a light background",
  "A stained glass window depicting a pizza and a soda",
  "A pencil and watercolor drawing of a bustling city in the future with hovering vehicles",
  "A sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel blue water, next to a big window, in digital art",
  "A fortune-telling dog reading your fate in a giant cookie, in digital art",
  "A sea otter with a diamond earring by Johannes Vermeer",
  "An oil pastel drawing of a curious cat in a spaceship",
  "A painting of a wolf in the style of Starry Night",
  "A bowl of soup that looks like a monster, knitted out of yarn",
  "A plush toy robot sitting against a blue wall",
  "A synthwave style sunrise above the reflecting water of the ocean, in digital art",
  "Two futuristic skyscrapers with a skybridge covered in lush greenery, in digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective waterfall",
  "A comic book cover of a superhero wearing sunglasses",
  "A centered explosion of sparkles on a white background",
  "A photo of a Golden Retriever with its tongue out hugging a black Persian cat",
  "A photo of a black fur monster standing in a pink room",
  "A photo of Michelangelo's sculpture of David wearing headphones DJing",
  "A Samurai riding a Horse on Venus, in lomography",
  "A modern, sleek Ferrari driving on a winding road with a picturesque mountain range in the background, with a lens flare, in 50mm photography",
  "A realistic photograph of a young man with brown eyes and black hair",
  "A woman standing in front of a portal to another dimension",
  "Spongebob Squarepants in the Ghostbusters",
  "A velociraptor working as a DJ, in lomography",
  "A woman walking through the bustling streets of Hong Kong at night, lit by many bright neon shop signs, in 50mm lens",
  "A BBQ that is alive, in the style of a Disney animated movie",
  "A futuristic cyborg dance club, with neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik’s cube, in professional food photography",
  "A Synthwave Hedgehog, in Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, in photography",
  "A Dinosaur exploring Sydney, in photography",
  "A Man falling in Love with his Smartphone, in digital",
    'an armchair in the shape of an avocado',
    'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
    'teddy bears shopping for groceries in Japan, ukiyo-e',
    'an oil painting by Matisse of a humanoid robot playing chess',
    'panda mad scientist mixing sparkling chemicals, digital art',
    "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
    '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
    'an astronaut lounging in a tropical resort in space, vaporwave',
    'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
    'a stained glass window depicting a hamburger and french fries',
    'a pencil and watercolor drawing of a bright city in the future with flying cars',
    'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
    'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
    'a sea otter with a pearl earring" by Johannes Vermeer',
    'an oil pastel drawing of an annoyed cat in a spaceship',
    'a painting of a fox in the style of Starry Night',
    'a bowl of soup that looks like a monster, knitted out of wool',
    'A plush toy robot sitting against a yellow wall',
    'A synthwave style sunset above the reflecting water of the sea, digital art',
    'Two futuristic towers with a skybridge covered in lush foliage, digital art',
    'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
    'A comic book cover of a superhero wearing headphones',
    'A centered explosion of colorful powder on a black background',
    'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
    'A photo of a white fur monster standing in a purple room',
    "A photo of Michelangelo's sculpture of David wearing headphones djing",
    'A Samurai riding a Horse on Mars, lomography.',
    'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
    'A realistic photograph of a young woman with blue eyes and blonde hair',
    'A man standing in front of a stargate to another dimension',
    'Spongebob Squarepants in the Blair Witch Project',
    'A velociraptor working at a hotdog stand, lomography',
    'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
    'A BBQ that is alive, in the style of a Pixar animated movie',
    'A futuristic cyborg dance club, neon lights',
    'The long-lost Star Wars 1990 Japanese Anime',
    'A hamburger in the shape of a Rubik’s cube, professional food photography',
    'A Synthwave Hedgehog, Blade Runner Cyberpunk',
    'An astronaut encountering an alien life form on a distant planet, photography',
    'A Dinosaur exploring Cape Town, photography',
    'A Man falling in Love with his Computer, digital art',
    'A photograph of a cyborg exploring Tokyo at night, lomography',
    'Dracula walking down the street of New York City in the 1920s, black and white photography',
    'Synthwave aeroplane',
    'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
    'A Space Shuttle flying above Cape Town, digital art',
  ];